import Head from 'next/head'
import Header from '../components/Header'
import News from '../components/News'
import Slider from '../components/Slider'

export default function Home() {
  return (
    <div>
      <Head>
        <title>karminecorp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Header />

      {/* VIDÉO */}
      <div className="absolute z-1 top-[100px] lg:top-[-100px]">
        <video autoPlay={true} loop={true} muted={true}>
          <source src="KARMINE_PAD.mp4" />
        </video>
        <Slider />
        <News />
      </div>

    </div>
  )
}
